name: flutter_base_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  flutter: 3.7.10
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  background_json_parser: ^1.0.4
  cached_network_image: ^3.2.3
  collection: any
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.1
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  firebase_core: ^2.15.0
  firebase_dynamic_links: ^5.3.4
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  get: ^4.6.5
  go_router: ^12.0.0
  intl: any
  logger: ^2.0.2+1
  overlay_kit: ^1.0.8
  package_info_plus: ^4.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: null
  dart_code_metrics: ^5.5.1
  flutter_gen_runner: null
  flutter_lints: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  async: ^2.8.2

flutter_gen:
  output: lib/app/constants/assets
  line_length: 120

  integrations:
    flutter_svg: true
  fonts:
    enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: GreycliffCF
      fonts:
        - asset: assets/fonts/GreycliffCF-Light.ttf
          weight: 300
        - asset: assets/fonts/GreycliffCF-Regular.ttf
          weight: 400
        - asset: assets/fonts/GreycliffCF-Medium.ttf
          weight: 500
        - asset: assets/fonts/GreycliffCF-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/GreycliffCF-Bold.ttf
          weight: 700
